// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: service-user/manage/manage.proto

package manage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Manage service

func NewManageEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Manage service

type ManageService interface {
	Query(ctx context.Context, in *UserQueryRequest, opts ...client.CallOption) (*UserQueryResponse, error)
}

type manageService struct {
	c    client.Client
	name string
}

func NewManageService(name string, c client.Client) ManageService {
	return &manageService{
		c:    c,
		name: name,
	}
}

func (c *manageService) Query(ctx context.Context, in *UserQueryRequest, opts ...client.CallOption) (*UserQueryResponse, error) {
	req := c.c.NewRequest(c.name, "Manage.Query", in)
	out := new(UserQueryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Manage service

type ManageHandler interface {
	Query(context.Context, *UserQueryRequest, *UserQueryResponse) error
}

func RegisterManageHandler(s server.Server, hdlr ManageHandler, opts ...server.HandlerOption) error {
	type manage interface {
		Query(ctx context.Context, in *UserQueryRequest, out *UserQueryResponse) error
	}
	type Manage struct {
		manage
	}
	h := &manageHandler{hdlr}
	return s.Handle(s.NewHandler(&Manage{h}, opts...))
}

type manageHandler struct {
	ManageHandler
}

func (h *manageHandler) Query(ctx context.Context, in *UserQueryRequest, out *UserQueryResponse) error {
	return h.ManageHandler.Query(ctx, in, out)
}
