// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.3
// source: service-user/manage/manage.proto

package manage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"required" tips:"required=用户字段必须填写"
	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty" validate:"required" tips:"required=用户字段必须填写"`
}

func (x *UserQueryRequest) Reset() {
	*x = UserQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_user_manage_manage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserQueryRequest) ProtoMessage() {}

func (x *UserQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_manage_manage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserQueryRequest.ProtoReflect.Descriptor instead.
func (*UserQueryRequest) Descriptor() ([]byte, []int) {
	return file_service_user_manage_manage_proto_rawDescGZIP(), []int{0}
}

func (x *UserQueryRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type UserQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *UserQueryResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserQueryResponse) Reset() {
	*x = UserQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_user_manage_manage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserQueryResponse) ProtoMessage() {}

func (x *UserQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_manage_manage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserQueryResponse.ProtoReflect.Descriptor instead.
func (*UserQueryResponse) Descriptor() ([]byte, []int) {
	return file_service_user_manage_manage_proto_rawDescGZIP(), []int{1}
}

func (x *UserQueryResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserQueryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserQueryResponse) GetData() *UserQueryResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserQueryResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      uint64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Nickname string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Phone    string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Email    string `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *UserQueryResponseData) Reset() {
	*x = UserQueryResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_user_manage_manage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserQueryResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserQueryResponseData) ProtoMessage() {}

func (x *UserQueryResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_manage_manage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserQueryResponseData.ProtoReflect.Descriptor instead.
func (*UserQueryResponseData) Descriptor() ([]byte, []int) {
	return file_service_user_manage_manage_proto_rawDescGZIP(), []int{2}
}

func (x *UserQueryResponseData) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserQueryResponseData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserQueryResponseData) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserQueryResponseData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserQueryResponseData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_service_user_manage_manage_proto protoreflect.FileDescriptor

var file_service_user_manage_manage_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x13, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x22, 0x24, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x81, 0x01,
	0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x3e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x8d, 0x01, 0x0a, 0x15, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x32, 0x62, 0x0a, 0x06, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x12, 0x58, 0x0a, 0x05, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x25, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x79, 0x72, 0x65, 0x61, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x3b, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_user_manage_manage_proto_rawDescOnce sync.Once
	file_service_user_manage_manage_proto_rawDescData = file_service_user_manage_manage_proto_rawDesc
)

func file_service_user_manage_manage_proto_rawDescGZIP() []byte {
	file_service_user_manage_manage_proto_rawDescOnce.Do(func() {
		file_service_user_manage_manage_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_user_manage_manage_proto_rawDescData)
	})
	return file_service_user_manage_manage_proto_rawDescData
}

var file_service_user_manage_manage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_user_manage_manage_proto_goTypes = []interface{}{
	(*UserQueryRequest)(nil),      // 0: service.user.manage.UserQueryRequest
	(*UserQueryResponse)(nil),     // 1: service.user.manage.UserQueryResponse
	(*UserQueryResponseData)(nil), // 2: service.user.manage.UserQueryResponseData
}
var file_service_user_manage_manage_proto_depIdxs = []int32{
	2, // 0: service.user.manage.UserQueryResponse.data:type_name -> service.user.manage.UserQueryResponseData
	0, // 1: service.user.manage.Manage.Query:input_type -> service.user.manage.UserQueryRequest
	1, // 2: service.user.manage.Manage.Query:output_type -> service.user.manage.UserQueryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_user_manage_manage_proto_init() }
func file_service_user_manage_manage_proto_init() {
	if File_service_user_manage_manage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_user_manage_manage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_user_manage_manage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_user_manage_manage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserQueryResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_user_manage_manage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_user_manage_manage_proto_goTypes,
		DependencyIndexes: file_service_user_manage_manage_proto_depIdxs,
		MessageInfos:      file_service_user_manage_manage_proto_msgTypes,
	}.Build()
	File_service_user_manage_manage_proto = out.File
	file_service_user_manage_manage_proto_rawDesc = nil
	file_service_user_manage_manage_proto_goTypes = nil
	file_service_user_manage_manage_proto_depIdxs = nil
}
